### ISSUE TITLE
nested defaults

### ISSUE THREAD

**Issue by martindurant** [ContinuumIO/intake#103]
If a source has parameters which include nested structures, e.g., `storage_options`, which is always a dictionary, there is no way to make a part of that structure a user parameter.

Could be fixed by recursively descending into standard argument containers and checking for jinja-like strings at all levels.

**Comment by seibert** [comment]
Easy discoverability was part of the motivation (vaguely, I had not thought about this scenario specifically) for having a distinct template string type in the YAML.  However, I agree that custom type was awkward to read, so I think the solution you propose here probably makes more sense.
