### ISSUE TITLE
Quickstart inconsistency

### ISSUE THREAD

**Issue by klucar** [ContinuumIO/intake#127]
There is an inconsistency in the Quickstart documentation. `intake example` creates the csv and catalog files in the current directory. The documentation says `intake.open_csv('civilservices/states_*.csv)` The read then fails because there is no `civilservices` directory. Not sure which is the intended location of the data, but the inconsistency makes the Quickstart fail.

**Comment by martindurant** [comment]
Fixed, thanks.
Also cleared up CATALOG_DIR when loading a file without a dir (i.e., in CWD).
