### ISSUE TITLE
Don't test with conda-build

### ISSUE THREAD

**Issue by martindurant** [ContinuumIO/intake#129]
The current workflow on Travis is to run conda-build, which is turn runs tests. This already caused one miss (not all tests were being run because of `--pyargs`). Travis should not be the place where packages are built, it should be for testing.
Suggest that 1) we run `pytest` directly and 2) later, move package builds to conda-forge. There is no longer any need to keep releases isolated. Note that following such a move, the first few releases should still be copied to the intake channel, for those that find installation instructions which refer to it.

**Comment by bryevdv** [comment]
I would suggest it's good to test package building itself, i.e. to validate that package building and installing can be successful, even if you move building release packages to C-F (better to find problems out early on Travis than during the middle of a release) But agree that other tests should just be run directly with `pytest`
