### ISSUE TITLE
Urls with globs for remote HTTP

### ISSUE THREAD

**Issue by mmccarty** [ContinuumIO/intake#133]
Currently data sources that attempt to cache on an HTTP glob string get a ``NotImplementedError`` from ``dask.bytes``.

I opened a related [issue](https://github.com/martindurant/filesystem_spec/issues/9) on the filesystem_spec repo to attempt to generate a discussion on this topic.

**Comment by martindurant** [comment]
https://github.com/dask/dask/pull/3926

**Comment by martindurant** [comment]
Also https://github.com/martindurant/filesystem_spec/pull/13

**Comment by martindurant** [comment]
Closing this for now. This is implemented in fsspec, which will replace open_files in intake probably in ~January.
