### ISSUE TITLE
RFC: CLI functions

### ISSUE THREAD

**Issue by martindurant** [ContinuumIO/intake#134]
The current client CLI is present, but not very prominent of featureful. Please comment here on requests for what the CLI should be capable of.

**Comment by martindurant** [comment]
cc @pzwang

**Comment by seibert** [comment]
I think being able to inspect the state of the cache and clear it would be useful.

**Comment by seibert** [comment]
maybe a subcommand to validate a catalog file parses correctly?

**Comment by seibert** [comment]
And a command to precache every source in a catalog file.  I could imagine calling that when building a docker image.

**Comment by mmccarty** [comment]
A command(s) to help validate and debug cache specs in a given catalog file.
