### ISSUE TITLE
Caching next steps

### ISSUE THREAD

**Issue by martindurant** [ContinuumIO/intake#136]
- to implement new cache "types", such as a directory-tree downloader (give root path and number of levels to glob, returns local directory root) and decompressor (refer to remote tar/gz/bz2/zip, download and unpack locally, returns local directory)
- provide a progress bar while downloading 
- download in multiple threads, one per file, using Dask

**Comment by jlstevens** [comment]
I agree that a download progress bar would be a huge improvement in the user experience. 

In the current notebook I am running, I initially thought ``intake`` was hanging. After waiting several minutes, the only reason I haven't given up and interrupted my notebook kernel is that I can see ``~/.intake/cache`` gradually filling up with files.

**Comment by mmccarty** [comment]
@martindurant @jlstevens @jbednar I'm working on the progress bar now.

**Comment by martindurant** [comment]
Is it worth reusing the dask one, if we can phrase the download as X delayed files download, and then also use parallelism? (obviously only works on single-node, or where workers have access tot the same filesystem)

**Comment by mmccarty** [comment]
Dask or tqdm are the current options.

**Comment by mmccarty** [comment]
Progress bar added in PR #138
