### ISSUE TITLE
Pick location of "default" catalog files

### ISSUE THREAD

**Issue by seibert** [ContinuumIO/intake#14]
Intake should have a "default" catalog composed from catalog files found in a standard location.
What should the search path for the catalog files be?

Proposal is to autoload `intake/catalog.d/*.{yaml,yml}` under the following directories:
- `$CONDA_PREFIX` - for conda-installable catalogs
- *What is the equivalent prefix for virtualenv?* - for pip-installable catalogs
- `~/.local/` - Linux user data dir
- `~/Library/` - macOS user data dir
- `%APPDATA%\` - Windows user data dir

The default catalog should be the union of all catalog files from these locations.

**Comment by martindurant** [comment]
Suggest to close

**Comment by seibert** [comment]
Yeah, this is done and implemented.
