### ISSUE TITLE
Progress Bars break in Jupyter Lab

### ISSUE THREAD

**Issue by mmccarty** [ContinuumIO/intake#148]
Instead of a progress bar you get 

`HBox(children=(IntProgress(value=0, description='100000_Sales_Records.csv', max=11), HTML(value='')))`

<img width="1084" alt="screen shot 2018-09-05 at 1 51 11 pm" src="https://user-images.githubusercontent.com/625946/45111358-c9ebc680-b112-11e8-8844-511b77cc5148.png">

**Comment by martindurant** [comment]
You would need the ipywidgets jlab extension to be installed https://ipywidgets.readthedocs.io/en/stable/user_install.html#installing-the-jupyterlab-extension

I don't think there's any way for us to determine from within the notebook whether the output works or not. There could be a config option to always use text progress bars, although I don't know if those would render well in the non TTY output area.

**Comment by martindurant** [comment]
@mmccarty , do you think it's enough to document that, when used in jlab, you need to explicitly enable the extension? Yes, it does work, I tried it.
Frankly, I'm surprised that conda-installing jupyter-widgets doesn't do this automatically, is there someone we should tag here to suggest that it should?

**Comment by martindurant** [comment]
@mmccarty , can you post upstream to tqdm?

**Comment by mmccarty** [comment]
https://github.com/tqdm/tqdm/issues/394 looks related.

**Comment by martindurant** [comment]
Commented on that issue. Closing this as something we can't do anything about (but I solved it for our own GUI).

**Comment by psarka** [comment]
Just wasted an hour on this... :(

**Comment by martindurant** [comment]
Did the explanation above correctly describe the situation for you, @psarka ? I believe you wouldn't see this if you installed things from conda versus pip (but I may be mistaken).

**Comment by psarka** [comment]
Yes, it was the widgets thing. It may be fixed by moving to conda, but my team has settled on using vanilla python.

Not sure if I have a suggestion for this situation, except maybe disabling the loading bars by default until https://github.com/tqdm/tqdm/issues/394 is fixed...

**Comment by martindurant** [comment]
Unfortunately, we can tell if we are in a notebook or but not whether the widget will actually render.

On February 4, 2019 10:41:39 AM EST, "Paulius Šarka" <notifications@github.com> wrote:
>Yes, it was the widgets thing. It may be fixed by moving to conda, but
>my team has settled on using vanilla python.
>
>Not sure if I have a suggestion for this situation, except maybe
>disabling the loading bars by default until
>https://github.com/tqdm/tqdm/issues/394 is fixed...
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/ContinuumIO/intake/issues/148#issuecomment-460295682

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mirekphd** [comment]
This problem re-emerged in one of our containers with Jupyter Notebook, raising this warning message on every call to `papermill.execute_notebook()`:

```
HBox(children=(FloatProgress(value=0.0, description='Executing', max=836.0, style=ProgressStyle(description_wi…

/opt/conda/lib/python3.8/site-packages/traitlets/config/configurable.py:73: DeprecationWarning: Passing unrecoginized arguments to super(PapermillNotebookClient).__init__(input_path='./mtpl-conversion-or-(risk)-premium-(change)-model.ipynb', nest_asyncio=True).
object.__init__() takes exactly one argument (the instance to initialize)
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Configurable, self).__init__(**kwargs)
```

The solution was to re-install (with conda) [jupyter_nbextensions_configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) and then to re-enable the extensions configuration option (the last one in Jupyter Notebook's Edit menu) for the current user, like this:

```
$ jupyter nbextensions_configurator enable --user
Enabling: jupyter_nbextensions_configurator
- Writing config: /home/jovyan/.jupyter
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 OK
Enabling notebook nbextension nbextensions_configurator/config_menu/main...
Enabling tree nbextension nbextensions_configurator/tree_tab/main...
```

The extension used by papermill for displaying progress bars (taken from `tqdm` package) is called `jupyter-js-widgets-extension` and it should be enabled in Jupyter Nbextensions Configurator to solve this issue (for the current user).

**Comment by martindurant** [comment]
Thanks for the report, @mirekphd . I've never used papermill, so it's nice to have people to check and fix these things for us.
