### ISSUE TITLE
Configure Intake to cache files in the current directory

### ISSUE THREAD

**Issue by mmccarty** [ContinuumIO/intake#151]
From @jbednar 

In most cases I'd rather have the files associated with the notebook or project where I'm working, not dumped into an ever-increasing global cache heap.
I would be nice to have a simple flag for configuring intake (something `intake.local_cache=True`) to store cached items in a subdirectory like `.intake_cache/` in the current directory.

**Comment by seibert** [comment]
I hadn't thought of this usage model, but I guess it would work in some cases.  I would definitely not want to make it the default behavior, as these cache directories are both invisible and hard for a CLI to discover without scanning your whole hard drive.

**Comment by martindurant** [comment]
This sounds pretty reasonable to me. The CLI would get file locations from the metadata, which would be small and remain in the (global) config directory. I would suggest `config['cache_dir'] = "datadir"` could do this (better names accepted).

**Comment by mmccarty** [comment]
Yeah, the CLI could look at the metadata which should avoid the need to scan the hard drive.

**Comment by jbednar** [comment]
> I would definitely not want to make it the default behavior, as these cache directories are both invisible and hard for a CLI to discover without scanning your whole hard drive.

It might make sense to make the directory not be invisible, e.g. `./intake_cache/`; there are pros and cons to doing that.  But there are problems with both approaches, i.e. putting cache files in cwd and in the home directory; in one case it's clear what would be affected by deleting that file, but hard to find all of them (though one can do `find ~ -name intake_cache`), and in the other it's easy to find all of them but hard to tell what any particular file is and whether it can be deleted without a major download cost in your future.

**Comment by jbednar** [comment]
> Yeah, the CLI could look at the metadata which should avoid the need to scan the hard drive.

That makes sense -- the metadata should be tiny in any reasonable case, and presumably no one should object to having that in their homedir.
