### ISSUE TITLE
Inaccessible file path for data catalog fails silently 

### ISSUE THREAD

**Issue by jmabry** [ContinuumIO/intake#159]
When trying to load a catalog yml file hosted S3, missing credentials will silently lead to an empty catalog. So the user executes,

```
In [1]: from intake import Catalog

In [2]: cat = Catalog("s3://foo/bar.yml")

In [3]: cat.yaml()
Out[3]: "sources:\n  bar:\n    args:\n      path: s3://foo/bar.yml\n    description: ''\n    driver: yaml_files_cat\n    metadata: {}\n"

```
and it's not obvious why there are no sources. 

For the case of s3 specifically, a quick check looks like:
```
def verify_credentials(cat_uri):
    """
    FIXME copied from data-layer-api
    The intake catalog will appear empty when trying to read a catalog yml
    file on s3 if the credentials are not supplied correctly.
    """
    if "s3:" not in cat_uri:
        return True

    fs = s3fs.S3FileSystem()
    cat_exists = fs.exists(cat_uri)
    if not cat_exists:
        err_msg = "Catalog file not found at {}. Check AWS credentials.".format(cat_uri)
        raise EnvironmentError(err_msg)
```

There are probably issues related to this as well if trying to open a local yml file in a directory that doesn't exist.

**Comment by jmabry** [comment]
I understand the intent and assume changing that pattern would break other pieces of code. One optIon would be to provide a boolean keyword arg like “sources_expected” and invoke the validation method as a user defined option. For our use case, we are opening the Catalog behind an API endpoint so some type of behavior to cause us to fail fast would be appreciated. A warning could also be helpful if you want to avoid complicating the function call signature.

**Comment by jmabry** [comment]
A third option might be to create an empty file if the file doesn’t exist. This would have raised a helpful  error

**Comment by martindurant** [comment]
The proper place to put this would be in intake.catalog.base.Catalog; you'll notice that the refresh rate `ttl` is handled here, for instance. I would call it allow_empty, and we can argue about whether it should be True of not for the different types of Catalog.

> create an empty file if the file doesn’t exist

That seems like unexpected behaviour from the user's point of view

**Comment by seibert** [comment]
I think there might be an unnecessary linkage between the handling of a catalog directory and a catalog file.  A catalog directory which might be initially empty and have new files appear during operation (like conda installing a data package while notebook is running).  A catalog file, local or remote, should exist when the catalog object for a file is created, otherwise simple typos in filenames are very hard to catch.

**Comment by martindurant** [comment]
Indeed, that could be the way to do it, @stsievert , have different defaults for allow_empty for the two file Catalog classes, **or** raise an exception in YAMLFileCatalog._load if nothing is found (and not change anything elsewhere). The latter is easier to implement.
