### ISSUE TITLE
In CSV plugin, `path_as_pattern` field columns should be known categories

### ISSUE THREAD

**Issue by jsignell** [ContinuumIO/intake#178]
In the path column on dask the paths are known categories, which is why they are parse-able before the data are read. It would be good if the `path_as_pattern` fields were also known in this same way. It is a little tricky because the mapping from paths to unique pattern-field values is not necessarily 1:1 so we can't just use the same cat.codes. I guess what we should do is declare a new category index with new codes  and field values and then map path codes to field codes. That should work.

**Comment by martindurant** [comment]
> the mapping from paths to unique pattern-field values is not necessarily 1:1

Why is this? Is there an anti-example? 

Are you thinking that the category mapping should be an input to the CSV reader, so that the correct value can be added within tasks, or should the codes be passed directly?

**Comment by jsignell** [comment]
For instance in the csv example there are 9 files representing 3 emissions scenarios and 3 models. The user won't have to input anything. I was just making notes for myself for later.
