### ISSUE TITLE
ImportError: cannot import name source

### ISSUE THREAD

**Issue by samirak93** [ContinuumIO/intake#191]
Hi,

I've installed intake using `conda install -c intake intake` but when I try to import it on Jupyter notebook, I get the below error.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-924f1ec0a922> in <module>()
----> 1 import intake

/Users/samirakumar/anaconda/lib/python2.7/site-packages/intake/__init__.py in <module>()
      5 __version__ = get_versions()['version']
      6 del get_versions
----> 7 from . import source
      8 from .source.base import Schema, DataSource
      9 from .catalog.base import Catalog, RemoteCatalog

ImportError: cannot import name source
```

Am I doing anything wrong? 
Any feedback would be appreciated. Sorry if I'm not posting issues in any format.

Thanks.

**Comment by martindurant** [comment]
Intake is not tested with py2, and there are therefore likely some things that don't work. See the discussion in https://github.com/ContinuumIO/intake/issues/166 . Given that many projects are dropping py2 support right now, it seems like an effort I would not want to spend to fix the compatibility. I ought to set the requirement correctly in the conda package, however.

**Comment by martindurant** [comment]
To be sure, a PR to implement py2 compatibility would be welcome! I assume the particular exception shown here would be fixed by
```
from __future__ import absolute_import
```
at the top of the file.

**Comment by martindurant** [comment]
@samirak93 , #192 makes intake usable in py2. You can pip-install from the branch and try it out, if you like.
