### ISSUE TITLE
Intake should do exponential backoff for https

### ISSUE THREAD

**Issue by jsignell** [ContinuumIO/intake#199]
I was getting 503s using the google cloud storage API and saw that in their docs they recommend an exponential backoff. I was wondering if that would be something that intake could support as a kwarg in the catalog. It would look something like this:

```python
from random import random
from time import sleep

def with_exponential_backoff(maximum_backoff=32):
    """
    Google Cloud Storage recommends using exponential backoff 
    when accessing the API. 
    
    https://cloud.google.com/storage/docs/exponential-backoff
    """
    n = backoff = 0
    while backoff < maximum_backoff:
        try:
            return cat.source().to_dask()
        except:
            backoff = min(2**n + random(), maximum_backoff)
            sleep(backoff)
            n += 1
```

**Comment by martindurant** [comment]
I'd say this belongs in gcsfs.core.GCSFileSystem._call (which already has retries, but not timed). Can you confirm that your error is happening within that function, or are retries needed elsewhere in gcsfs?

**Comment by martindurant** [comment]
I was wrong, though, the retries in `_call()` is indeed exponential. The *data* access methods are not retried (in `_fetch`, `_initiate_uload`, `_upload_chunk`), though.
