### ISSUE TITLE
Finish documentation-related TBDs

### ISSUE THREAD

**Issue by seibert** [ContinuumIO/intake#20]
- Finish Quickstart with final catalog syntax
- Fix docstrings in API docs
- Implement !template_int and !template_datetime
- Implement shell() and env() for catalog files
- Decide on zero-length dataframe for metadata
- Better description of Intake uses in overview

**Comment by martindurant** [comment]
Closing this. Not that documentation is complete or comprehensive, but most of what is here is done, and we should have more specific docs issues.
