### ISSUE TITLE
For discussion: getattr -> getitem is good, but the inverse is confusing

### ISSUE THREAD

**Issue by danielballan** [ContinuumIO/intake#203]
Intake goes further than pandas in blurring the line between attribute access and item access. I would like explore the possibility of moving to behavior more like pandas.

To review pandas behavior:

```py
In [7]: import pandas                                                                                                                                         

In [8]: df = pandas.DataFrame({'a': [1, 2]})                                                                                                                  

In [9]: df['a']                                                                                                                                               
Out[9]: 
0    1
1    2
Name: a, dtype: int64

In [10]: df.a  # a convenient alias                                                            
Out[10]: 
0    1
1    2
Name: a, dtype: int64

In [11]: df.sum  # This is part of the DataFrame API, not a column.                                                                                           
Out[11]: 
<bound method DataFrame.sum of    a
0  1
1  2>

In [12]: df['sum']  # This is a KeyError.
<snip>
KeyError: 'sum'
```

So, to summarize, `__getattr__` falls back to `__getitem__`, but not the other way around. Intake maps in both directions:

```py
In [1]: import intake                                                                                                                                         

In [2]: cat = intake.open_catalog('intake/cli/sample/us_states.yml')                                                                                          

In [3]: cat['states']                                                                                                                                         
Out[3]: <Catalog Entry: states>

In [4]: cat.states  # a convenient alias, a la pandas                                                                                                         
Out[4]: <Catalog Entry: states>

In [5]: cat.metadata  # this part of the Category API, not an entry                                                                                           
Out[5]: {}

In [6]: cat['metadata']  # I would not expect this to work, but it does.                                                                                      
Out[6]: {}
```

Anecdotally, it took me a day or two with intake to recognize that this was happening, and in my week or two working with the library it's made some debugging more subtle.

**Comment by jsignell** [comment]
I think that seems like a very reasonable proposal and I doubt it would break any existing code.

**Comment by martindurant** [comment]
Thanks @danielballan for the clear explanation. I don't think I had initially understood what you meant. I agree with the gist, that `cat[thing]` should retrieve an entry, but not an attribute otherwise belonging to the Catalog object, and raise `KeyError` (or internal "no such data-set") if it doesn't exist. 

`cat.thing` should get the attribute, if it exists, and attempt to get an entry if not, and raise `AttributeError` if both fail.

I note that using YAML as the main input means that entry names will tend to be valid python identifiers, but this is not guaranteed, especially for cats that don't come from YAML, and so the item route should continue to exist.

**Comment by danielballan** [comment]
Thanks, all. Agreed with all of the above. I will draft a PR shortly and we can verify through tests that we are on the same page about the details.

**Comment by mmccarty** [comment]
Thanks @danielballan Following Pandas' behavior is a good way to go. I look forward to seeing the PR.

**Comment by danielballan** [comment]
Since this would collide badly with #200 I'm going to wait for that to get in before submitting said PR.

**Comment by martindurant** [comment]
Sounds reasonable. Are you still working on #200 ?

**Comment by danielballan** [comment]
It's ready for another round of review. There are some open questions I left that may prompt some follow-up work, but it's in a working state now (modulo rebase).
