### ISSUE TITLE
Documentation refers to non-existing function

### ISSUE THREAD

**Issue by smoh** [ContinuumIO/intake#209]
The documentation tells me in [Catalogs](https://intake.readthedocs.io/en/latest/catalog.html) section that it's possible to use `load_catalog` method to load everything inside a directory like
```python
from intake import load_catalog

cat = load_catalog('/research/my_project/catalog.d/')
```
yet there is no `load_catalog` function exposed!

```python
In [1]: import intake

In [2]: intake.__version__
Out[2]: '0.3.0'

In [3]: from intake import load_catalog
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-60cae778b6d2> in <module>
----> 1 from intake import load_catalog

ImportError: cannot import name 'load_catalog' from 'intake' (/Users/semyeong/miniconda3/envs/research/lib/python3.7/site-packages/intake/__init__.py)
```

Two questions:
- Is there another way to have that functionality? (grab every catalog yamls inside a directory)
- I discovered that there is `intake.load_combo_catalog`: is this here to stay? If so, how is user_dir and global_dir controlled?

Thanks.

**Comment by smoh** [comment]
Thanks for your reply. I noticed that indeed in the `open_catalog` docstring there is this item:
```
- if ``uri`` is a list of strings, a string containing a glob character
  ("*") or a string not ending in "y(a)ml", open as a set of catalog
  files. In the latter case, assume it is a directory
```
However, it looks like when doing `open_catalog('/path/to/directory')`, it will scan whatever file inside as Catalog Yaml regardless of file extensions.

I have a directory structure such as
```
basedir/
    dataset1/
        dataset1.yaml
        file1.csv
        file2.csv
    dataset2/
        dataset2.yaml
        file1.csv
        file2.csv
```
and I tried `open_catalog('basedir/dataset1')` to get an error like (not a full traceback)
```python

~/miniconda3/envs/research/lib/python3.7/site-packages/intake/catalog/local.py in __init__(self, path, **kwargs)
    528         """
    529         self.path = path
--> 530         super(YAMLFileCatalog, self).__init__(**kwargs)
    531 
    532     def _load(self):

~/miniconda3/envs/research/lib/python3.7/site-packages/intake/catalog/base.py in __init__(self, *args, **kwargs)
     75         self.updated = time.time()
     76         self._entries = {}
---> 77         self.force_reload()
     78 
     79     def _load(self):

~/miniconda3/envs/research/lib/python3.7/site-packages/intake/catalog/base.py in force_reload(self)
     83     def force_reload(self):
     84         """Imperative reload data now"""
---> 85         self._load()
     86         self.updated = time.time()
     87 

~/miniconda3/envs/research/lib/python3.7/site-packages/intake/catalog/local.py in _load(self)
    566             raise exceptions.ValidationError(
    567                 "Catalog '{}' has validation errors:\n\n{}"
--> 568                 "".format(self.path, "\n".join(result.errors)), result.errors)
    569 
    570         cfg = result.data

ValidationError: Catalog '...file1.csv' has validation errors:
```

What I really wanted to do was to be able to do something like `open_catalog('basedir')` which will parse all yaml catalog files so that I can have one object from which I can load whatever "Catalog" I want to -- is this possible? (Unclear is what `a set of catalog` looks like or whether it's possible for `open_catalog` to handle multiple yamls)

I also tried something like:
```
basedir/
    dataset1/
        file1.csv
        file2.csv
    dataset2/
        file1.csv
        file2.csv
dataset1.yaml
dataset2.yaml
```
and do `open_catalog('basedir')` or `open_catalog('basedir/*.yaml')` but get an empty catalog instance.

**Comment by martindurant** [comment]
Indeed, I noticed and fixed this in the latest commit. If you don't wish to update to master, you can continue using and explicit glob string for now, which in your case would be `"basedir/data*/*.yaml"`; but yes, you could pass an explicit list of paths too, or indeed a list of glob strings.

Note that the implementation of all of this is in `intake.catalog.local.YAMLFilesCatalog`, which you can access directly with `intake.open_yaml_files_cat`, if you wish.

**Comment by smoh** [comment]
I see, thanks for a prompt response. I confirm that it works with explicit glob string like "basedir/data*/*.yaml" or a list of yaml files.

By the way, I was almost thought it still didn't work because the `__repr__` still returned
```
<Intake catalog: None>
```
when the returned object does contain the right catalogs when I do list(). Something to improve in future perhaps?

Many thanks.

**Comment by martindurant** [comment]
Please raise that as a separate issue, and I will deal with it. You may want to propose the correct thing to show instead of `None` for a potentially complicated case of multiple files/directories.
