### ISSUE TITLE
Adding extra drivers on-the-fly

### ISSUE THREAD

**Issue by smoh** [ContinuumIO/intake#216]
1. I am trying to add a module containing my custom "Driver" on-the-fly following the documentation.

I have the following in my current directory
```
└── data
    ├── catalog.yaml
    ├── example.csv
    └── intake_astropy.py
```

```yaml
# ==> data/catalog.yaml <==
metadata:
  version: 1

plugins:
  source:
    - module: intake_astropy
    - dir: "{{ CATALOG_DIR }}"

sources:

  example:
    driver: astropy_table
    args:
      path: "{{ CATALOG_DIR }}/example.csv"
      args:
        format: ascii.csv
```

==> data/example.csv <==
```csv
col1, col2, col3
1, 2, 3
```

==> data/intake_astropy.py <==
```python
'''
Astropy Table driver for Intake
'''
from intake.source.base import DataSource
from astropy.table import Table
import pandas as pd
import intake


__all__ = ['AstropyTableSource']


class AstropyTableSource(DataSource):
    container = 'dataframe'
    name = 'astropy_table'
    version = '0.0.1'
    partition_access = False

    def __init__(self, path, metadata=None, **kwargs):
        super(AstropyTableSource, self).__init__(metadata=metadata)
        self.path = path
        self.kwargs = kwargs

    def _get_schema(self):
        t = Table.read(self.path, **self.kwargs)
        return intake.source.base.Schema(
            datashape=None
        )

    def read(self):
        t = Table.read(self.path, **self.kwargs)
        return t.to_pandas()

    def _close(self):
        pass
```

Now I try to read:
```python
In [1]: import intake

In [2]: cat = intake.open_catalog('data/catalog.yaml')

In [3]: cat.example.get()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-b8364f147845> in <module>
----> 1 cat.example.get()

~/miniconda3/envs/research/lib/python3.7/site-packages/intake/catalog/local.py in get(self, **user_parameters)
    235         if len(self._plugin) == 0:
    236             raise ValueError('No plugins loaded for this entry: %s'
--> 237                              % self._driver)
    238         elif isinstance(self._plugin, list):
    239             plugin = self._plugin[0]

ValueError: No plugins loaded for this entry: astropy_table
```

I tried with `driver: intake_astropy.AstropyTableSource` or `driver: AstropyTableSource` and got the same error.

What am I doing wrong here?

2. Is there a way to express "parent dir of CATALOG_DIR" using jinja?

```
plugins:
    dir: "{{CATALOG_DIR}}/.."
````
Does this work?

3. Finally, if a user is inside the directory where the driver module is (`intake_astropy.py`), this import statement
```
from intake.source.base import DataSource
```
gives
```
In [1]: import intake
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-924f1ec0a922> in <module>
----> 1 import intake

~/miniconda3/envs/research/lib/python3.7/site-packages/intake/__init__.py in <module>
     69
     70
---> 71 make_open_functions()
     72 cat = load_combo_catalog()
     73

~/miniconda3/envs/research/lib/python3.7/site-packages/intake/__init__.py in make_open_functions()
     36         isidentifier = IDENTIFIER_REGEX.match
     37     for plugin_name, plugin in registry.items():
---> 38         func_name = 'open_' + plugin_name
     39         if not isidentifier(func_name):
     40             # primitive name normalization

TypeError: can only concatenate str (not "NoneType") to str
```

I'm guessing this is because it's recognizing the base class as a plugin driver?

If I remove that import statement and instead subclass like
```python
class AstropyTableSource(intake.source.base.DataSource):
```
everything works
```python
In [1]: import intake

In [2]: intake.open_astropy_table
Out[2]: intake_astropy.AstropyTableSource
```

(Obviously, I was trying this because I want to use other parsing capabilities of astropy not csv)

**Comment by martindurant** [comment]
Before I answer your specific question, are you aware of [intake-astro](https://github.com/ContinuumIO/intake-astro) ?

**Comment by smoh** [comment]
Yes, I used it as a reference. It didn't fit my purpose because a) I am trying to parse many astro-specific ascii tables/xml votables (which would be a nice addition to intake-astro) and b) I want to experiment doing more than simply reading with on-the-fly way.

**Comment by martindurant** [comment]
> I'm guessing this is because it's recognizing the base class as a plugin driver

Yes, that seems to be true, and should be special-cased in the scanning code (and errors in making the open functions should print a warning and skip on, instead of failing)

> driver: intake_astropy.AstropyTableSource

This form will work if `intake_astropy` is an importable module, i.e., on your python PATH (which usually includes the cwd). That would be typical usage where you require an installed package as the driver.

In fact, any package (importable thing) that is found whose name begins with "intake_` and has DataSource derivative classes in the top level will have those classes added to the registry on import of intake, so you would not need the source: section at all, and can just refer to the driver by name, as you were trying to do.

> dir: "{{ CATALOG_DIR }}"

I don't know why this isn't finding your driver. Perhaps you check the `._catalog_dir` attribute of the catalog instance, try reading the catalog using the absolute path, adding a '/' to the path given... not sure. There are tests that seem to do exactly this and work.

> from astropy.table import Table

Generally prefer deferring imports until after instantiation of the source, e.g., in the _get_schema method, since many things might potentially be imported when intake first loads. That can complicate finding out why a driver didn't appear - perhaps something else went wrong during import (circular dependencies, etc).

**Comment by martindurant** [comment]
Sorry, the attribute is `._dir`, or the `._catalog_dir` of the *entry*. I see it get correctly expanded.

**Comment by martindurant** [comment]
Bug found, fix coming

**Comment by martindurant** [comment]
Errant commas in the test source file caused incorrect compensation in the directory scanning code.

**Comment by smoh** [comment]
Should that fix the issue? The strange thing is I think the intake did find and execute my python module correctly because I see pyc file I didn't create otherwise, but I'm just not sure why it is not associating that with the driver I specified in the source specification.

> In fact, any package (importable thing) that is found whose name begins with "intake_` and has DataSource derivative classes in the top level will have those classes added to the registry on import of intake, so you would not need the source: section at all, and can just refer to the driver by name, as you were trying to do.

But in this case, to be consistent with `intake_<drivername>` rule, shouldn't I change `name` attribute to `astropy`?

Regardless of this, if I specify my module `random_module_name.py` (containing subclass of `DataSource` with `name=myrandomname` in `plugins:`, the correct `driver` value is `driver: myrandomname`, right?

**Comment by martindurant** [comment]
Yes, the PR will fix the issue. Your module was getting imported, but the name was having only its first letter used, you will have had a driver called "a" :|

You named things correctly: intake_astropy for the module/package (perhaps released as intake-astropy on pypi conda when the time is right), and astropy_table as the driver name. The auto-generated function would be open_astropy_table, if the module gets auto-loaded.

**Comment by martindurant** [comment]
Note that I am leaving on holiday this coming week, so you will probably not see feedback from me for a while.
