### ISSUE TITLE
Travis for vanilla python

### ISSUE THREAD

**Issue by psarka** [ContinuumIO/intake#251]
Currently travis is running tests in the conda environment. Since intake should work in vanilla python environments, travis could test that as well.

I'm raising this as currently intake is broken when running outside conda (see https://github.com/ContinuumIO/intake/pull/249).

If you agree, I can submit a PR that implements this.

**Comment by martindurant** [comment]
Agreed that we could, in principle, have an additional entry in the travis matrix which does `pip install -e .` (plus test requirements) and then tests the source directly. Would you be interested in contributing that?

**Comment by psarka** [comment]
Yes, I'll do it.
