### ISSUE TITLE
Caching SQL queries with expiration custom driver

### ISSUE THREAD

**Issue by costrouc** [ContinuumIO/intake#273]
Currently using a custom intake data source from SQL and looking to use some of the caching behavior with partitions. I have looked at the intake-sql and intake-odbc drivers and did not see that they implemented caching. I am wondering what is the correct way to implement caching as a file with expiration as I didn't see any examples

**Comment by martindurant** [comment]
I am so glad you asked!

See PR #237 

In Intake, we refer to "cache" to mean keeping local copied of remote *files*, unchanged. The functionality you are looking for is called *persist* (I can see these two ought to go into the glossary). The linked PR is implementing this, and you are very welcome to try it out.

 For the SQL case, it would write the results of the query (I'm assuming a data-frame) to local parquet files. An attempt to access the query will instead give you the local version, until a certain time passes, after which it will be refreshed.

**Comment by costrouc** [comment]
That's great! Thanks. I look forward to the PR getting merged.
