### ISSUE TITLE
RFC: Future container types

### ISSUE THREAD

**Issue by martindurant** [ContinuumIO/intake#43]
List possible additions to [python, array, dataframe] that Intake should consider.

**Comment by jakirkham** [comment]
Curious as to how easy it would be to add an HDF5 container as an example.

**Comment by martindurant** [comment]
@jakirkham , a plugin in hdf5->dataframe or hdf5->array is easy to make without changing intake; but the new container type you mean would presumably be xarray.

**Comment by mmccarty** [comment]
👍 for xarray

**Comment by mmccarty** [comment]
[Issue](https://github.com/ContinuumIO/intake/issues/54) for xarray containers
