### ISSUE TITLE
Working with partitioned data

### ISSUE THREAD

**Issue by ah-** [ContinuumIO/intake#71]
Hi,

What are your plans around using intake with large partitioned datasets, where you typically want to read just a subset of the data?

For example to access something like https://aws.amazon.com/public-datasets/landsat/ or hive-style partitioned parquet files?
E.g. a folder structure like
```
root/Metric=ABC/Date=2018-01-01/{lots of parquet files}
```

If I didn't miss anything it looks like the current support for partitioned data only covers the case of having multiple files in one folder and wanting to read all of them.

It'd be great to be able to read partitioned data, e.g. as `cat.dataset.read({'Metric': 'ABC', 'Date': '2018-01-01'})` or similar.

Ideally this would also integrate with hive and similar systems to fetch the partitions.

**Comment by martindurant** [comment]
The effect of partitioning will depend upon the plugin being used. One partition per file is typical for some, and there are some that have no partitioning at all (single download from some data server). Clearly this affects the usability for big-data applications. 

For the parquet-specific example, partitioning will be the same as in the underlying files, which will be one or more partitions per file - files can get rather large. Yes, you can specify `column=` and `filters=` keywords when using `open_parquet` or in a catalogue, and these are interpreted the same as in `fastparquet`, the library being used. Furthermore, you can use `.to_dask()` to get a big-data lazy pseudo-dataframe and manipulate this in various ways without loading everything into memory.

**Comment by ah-** [comment]
Not yet quite sure what to ask for exactly, but the use case I'm after involve having a pretty huge number of partitions, and then wanting them down before anything even goes into dask or I need to look up metadata/list files in that partition.

Imagine you have 50.000 metrics, and a file per day each. You want to have a look at a subset of that, e.g. 1000 metrics for the last year each, and then get that as a dask dataframe.

If you get a dask dataframe first and then start filtering you suffer from quite a lot of overhead.

**Comment by martindurant** [comment]
No, the whole purpose of a dask dataframe is to be able to filter your columns and apply other transformations to your data in a lazy fashion, before you actually download any data - any so be able to make smart decisions about which data to actually fetch. 

Note that 50,000 columns is rather extreme for parquet and you may well find that the metadata associated with the files, and the time taken to parse it, outweighs the data itself.

**Comment by talebzeghmi** [comment]
I'm also looking to add support to bind a dataset by partition by name.  
Something like `cat.dataset.read_partition({'zip_code': '98125', 'date': '2018-01-01'})`.  Or `cat.dataset.read_partition({'userId', '4323'})` for a serving layer plugin, say Redis.  I'd prefer the dataset be consistent and return a pandas DF instead of a Dask/Spark DF and then perform filtering there.  

As part of this, it'd be great to declare the partition_keys as part of the logical dataset catalog description.
```yaml
customer_attributes:
  args:
    urlpath: s3://path/date={{date}}/zip_code={{zip_code}}
  driver: parquet
  partition_keys: 
    - date
    - zip_code
```

**Comment by martindurant** [comment]
This feels rather specific to SQL-like functionality. A couple of notes:

- An argument like "{{ CATALOG_DIR }}/data/user/date={{date}}/zip_code={{zip_code}}" cal already be template-filled with either "user_parameters" (which have default) or direct override in the call. The allowed set of values could be made at run-time
- `source._get_partition(self, i)` already exists, and takes arbitrary input, in the simplest case an integer 0..npartitions. This is used, for instance, in grabbing the chunks of a remote N-D array, but could be made more prominent. The output is indeed blocking, not lazy.
- for the example YAML syntax, I would argue that all of the keys aside from "driver" are actually arguments, and will be used when instantiating the source, which acts a bit like a mini-catalogue for the possible set of storage parameters.
