### ISSUE TITLE
Slow import

### ISSUE THREAD

**Issue by martindurant** [ContinuumIO/intake#73]
Because intake automatically import all plugins it finds, importing intake is pretty slow and getting slower. Suggest we consider some method to take note of the plugin names that are importable, but only import them upon the use of an `open_*` function, or while loading a catalogue referencing given plugin.

**Comment by seibert** [comment]
Yeah, we could replace these with thunks that defer the import until the first usage.

**Comment by seibert** [comment]
Actually, thinking about this further, the name of the plugin is a currently an attribute of the Plugin subclass, so we do have to import the plugins in order to even populate the `open_*` functions and the plugin registry.

**Comment by martindurant** [comment]
There could be a convention that the `__init__` modules define the plugin, and import intake to do it, but source and all functionality is always in another module which is only imported when the plugin is used.

**Comment by martindurant** [comment]
To close this issue, I suggest that documentation should appear in the make-a-plugin page, describing the pattern.

**Comment by martindurant** [comment]
Example for intake-avro https://github.com/ContinuumIO/intake-avro/pull/4/commits/9e6f10e76c21cad8b0f43a2da050bfb2e6f43a1e
