### ISSUE TITLE
Authorization plugins for intake server

### ISSUE THREAD

**Issue by seibert** [ContinuumIO/intake#80]
In order to keep the core of Intake lightweight, while allowing for the customization of authorization policies for a catalog server, we should have a simple way to plugin a custom class to handle these decisions.  Note that the scope here is authorization, not authentication.  Authentication should basically always be handled by reverse proxy (like nginx) sitting in front of Intake which can populate (and strip) verified HTTP headers before passing the request to the Intake server.

Here are some proposed specs for discussion:

An authorization plugin class is a subclass of `intake.auth.AuthorizationPlugin` which requires the following methods to be implemented:

- `allow_connect(http_headers)`: Return `True` if the HTTP connection to the server should be allowed.  The `http_headers` dictionary contains all the headers from the HTTP request.  Reverse proxies can insert any information they like (such as authenticated user names or tokens) into the HTTP headers before passing along to Intake.  This function needs to be fast, as it is called for every request.
- `allow_access(http_headers, catalog_entry)`: Return `True` if the catalog entry (instance of `intake.catalog.entry.CatalogEntry`) should be visible to the client.  This is called for every catalog entry when the user requests a list of sources, and it is called once when the user initially tries to open a source.  The plugin can use any static metadata on the catalog entry to make the authorization decision, as well as the HTTP headers.  This allows use cases, like putting user and group names in the catalog entry metadata to control visibility.

To allow the plugin to be more easily instantiated with custom options, it will be activated via the planned catalog metadata section (see #75).  For example:
``` yaml
meta:
  version: 1
  authorization:
    plugin_class: intake_ldap_auth.AuthPlugin
    args:
      domain_controller: ldap.example.com
      dn: dc=exampledomain,dc=myorg
```
Only one authorization plugin can be active for a given server (if none is selected, the current behavior of "allow everything" continues).  If more than one is found, an error is raised and the server aborts.  In most cases, the auth plugin will be in a catalog file that is empty other than the `meta` section.

[edit: put the arguments to the class constructor into an args dict]

**Comment by seibert** [comment]
Correct, this is only relevant when using the intake server.

The main reason I wanted to have only one auth plugin active per server process is to make it easier to keep the auth configuration separate and orthogonal from the data source configuration.  Having a single server using multiple authentication methods doesn't make sense to me, since it isn't clear which plugin would be responsible for authorizing connections that are not tied to a specific catalog entry.  If multiple authorization schemes are desirable, two servers should be started looking at the same catalog files, but with different auth plugins enabled.

On reflection, abusing the catalog syntax to specify the auth plugin is a mistake, since the auth configuration really has nothing to do with catalogs themselves anyway.  Maybe it is time to introduce a server config yaml just for controlling things like the auth plugin, the port and IP addresses to listen on, etc.

**Comment by seibert** [comment]
The server has two basic URLs, which return and receive msgpack structures

* GET /v1/info - Returns a dictionary containing the server version (which is currently hardcoded and should instead be using versioneer now that we have it) and a list of catalog entry descriptions which are available.
* POST /v1/source - Perform an action on a data source based on the msgpack record that is posted.  The allowed actions are `open` and `read`.  Open returns a token (along with the source metadata) to the client.  This token must be presented in future `read` calls, which return a specific partition of the data source.

**Comment by seibert** [comment]
Yeah, it is passed straight through to the `read_partition` call.

Also, I now think we would likely want to check `allow_access` on every request to `/v1/source` (not just open), so that if authorization is revoked after the source has been opened, future requests are denied.

**Comment by martindurant** [comment]
@seibert , a flaw here is that the base URL, e.g., `http://localhost:5000` always connects successfully, even though the API endpoints are secured. This is good, because it allows the tests to check when the server is ready. I don't think the web-page ought to be used, it should be JSON endpoints on, and the bare URL, wherever it is defined, should just say "OK" to indicate the server is running.
