### ISSUE TITLE
Develop a jupyter-lab simple data browser pane

### ISSUE THREAD

**Issue by martindurant** [ContinuumIO/intake#95]
Idea from https://github.com/pangeo-data/pangeo/issues/39#issuecomment-389519782

**Comment by seibert** [comment]
This looks like a great example to follow: https://github.com/eWaterCycle/jupyterlab_thredds

**Comment by johngroves** [comment]
I have an initial JupyterLab extension working with a remote catalog, I can open a PR if it is helpful. The extension sends a request to the /v1/info endpoint, presents a list of sources, and provides code for loading the data. 

To do this, I've had to Dockerize the intake server and implement an nginx proxy to avoid CORS issues. Is there another endpoint for catalog discovery?


![intake_data](https://user-images.githubusercontent.com/10951009/42913880-31ba7744-8aac-11e8-9c83-f19d65c9fed7.gif)

**Comment by martindurant** [comment]
This is a great start, thank you!
Yes, please open a PR, so we can discuss.
I assume that in your panel, the URI to poke for datasets is pre-determined? By working with the server HTTP endpoint, there is no python logic at all, correct?

**Comment by seibert** [comment]
This is very exciting!  We had imagined this having a Python kernel behind it (which is what the threadds extension does), so that you would not have to deal with CORS issues, and it would also allow the browser to see local catalogs on the filesystem (including the default catalog in `intake.cat`).

To echo Martin's suggestion: Feel free to open an WIP PR and we can discuss further.

**Comment by martindurant** [comment]
Please don't hesitate to get in direct touch with us if you need some help here.

**Comment by johngroves** [comment]
@martindurant Apologies for dropping off here. Is anyone working on a Jupyterlab extension, or is the new GUI providing the desired functionality?

**Comment by martindurant** [comment]
The new GUI can be used in a notebook or standalone, but no one is working specifically on a j-lab pane. Having such a pane, perhaps a separate process or perhaps sharing state with a kernel running one of the notebooks, could be useful.
